# Generated by Django 5.0 on 2023-12-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=1000)),
                ('apellido_paterno', models.CharField(max_length=1000)),
                ('apellido_materno', models.CharField(max_length=1000)),
                ('dni', models.PositiveSmallIntegerField()),
                ('fecha_nac', models.DateField()),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
